package sop_corba;


/**
* sop_corba/_ServidorIntStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaz.idl
* martes 29 de mayo de 2018 07H47' COT
*/

public class _ServidorIntStub extends org.omg.CORBA.portable.ObjectImpl implements sop_corba.ServidorInt
{

  public boolean registrarCliente (sop_corba.ClienteInt objcllbck, String usuario)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registrarCliente", true);
                sop_corba.ClienteIntHelper.write ($out, objcllbck);
                $out.write_string (usuario);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return registrarCliente (objcllbck, usuario        );
            } finally {
                _releaseReply ($in);
            }
  } // registrarCliente

  public void enviarMensaje (String usuario, String mensaje)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("enviarMensaje", true);
                $out.write_string (usuario);
                $out.write_string (mensaje);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                enviarMensaje (usuario, mensaje        );
            } finally {
                _releaseReply ($in);
            }
  } // enviarMensaje

  public boolean desconectarCliente (sop_corba.ClienteInt objcllbck, String usuario)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("desconectarCliente", true);
                sop_corba.ClienteIntHelper.write ($out, objcllbck);
                $out.write_string (usuario);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return desconectarCliente (objcllbck, usuario        );
            } finally {
                _releaseReply ($in);
            }
  } // desconectarCliente

  public sop_corba.ServidorIntPackage.datosUsuario[] obtenerUsuariosConectados ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("obtenerUsuariosConectados", true);
                $in = _invoke ($out);
                sop_corba.ServidorIntPackage.datosUsuario $result[] = sop_corba.ServidorIntPackage.ListUsuariosHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return obtenerUsuariosConectados (        );
            } finally {
                _releaseReply ($in);
            }
  } // obtenerUsuariosConectados

  public boolean establecerSesionPriv (String usuario1, String usuario2)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("establecerSesionPriv", true);
                $out.write_string (usuario1);
                $out.write_string (usuario2);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return establecerSesionPriv (usuario1, usuario2        );
            } finally {
                _releaseReply ($in);
            }
  } // establecerSesionPriv

  public boolean enviarMensajePriv (String us1, String us2, String mensaje)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("enviarMensajePriv", true);
                $out.write_string (us1);
                $out.write_string (us2);
                $out.write_string (mensaje);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return enviarMensajePriv (us1, us2, mensaje        );
            } finally {
                _releaseReply ($in);
            }
  } // enviarMensajePriv

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/ServidorInt:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _ServidorIntStub
