package sop_corba;


/**
* sop_corba/ClienteInt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaz.idl
* martes 29 de mayo de 2018 07H47' COT
*/

public interface ClienteInt extends ClienteIntOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ClienteInt
