package sop_corba;


/**
* sop_corba/ClienteIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaz.idl
* martes 29 de mayo de 2018 07H47' COT
*/

public interface ClienteIntOperations 
{
  void recibirMensaje (String usuario, String mensaje);
  void establecerSesionPrivada (String usuario);
  void recibirMensajePrivado (String usuario, String mensaje);
  void recibirContacto (String usuario);
  String obtenerNombre ();
  void borrarListaDeContactos ();
} // interface ClienteIntOperations
