package sop_corba;


/**
* sop_corba/ServidorIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaz.idl
* martes 29 de mayo de 2018 07H47' COT
*/

public interface ServidorIntOperations 
{
  boolean registrarCliente (sop_corba.ClienteInt objcllbck, String usuario);
  void enviarMensaje (String usuario, String mensaje);
  boolean desconectarCliente (sop_corba.ClienteInt objcllbck, String usuario);
  sop_corba.ServidorIntPackage.datosUsuario[] obtenerUsuariosConectados ();
  boolean establecerSesionPriv (String usuario1, String usuario2);
  boolean enviarMensajePriv (String us1, String us2, String mensaje);
} // interface ServidorIntOperations
