package sop_corba.ServidorIntPackage;


/**
* sop_corba/ServidorIntPackage/datosUsuario.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaz.idl
* martes 29 de mayo de 2018 07H47' COT
*/

public final class datosUsuario implements org.omg.CORBA.portable.IDLEntity
{
  public String nombre = null;

  public datosUsuario ()
  {
  } // ctor

  public datosUsuario (String _nombre)
  {
    nombre = _nombre;
  } // ctor

} // class datosUsuario
